"""Tests needing no reference panel and no model"""
from __future__ import annotations

import os
import sys
import tempfile

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from g25 import chipio, harmonize as hz
from g25.panel import _unpack
from g25.pca import standardization, standardize
from g25.project import (RestrictedBasis, apply_calibration, fit_calibration,
                         lsq_per_individual)

FAILED = []


def check(name, cond, detail=""):
    if cond:
        print("  ok    %s" % name)
    else:
        print("  FAIL  %s  %s" % (name, detail))
        FAILED.append(name)


def test_chip_formats():
    print("vendor raw data formats")
    rows = [("rs1", 1, 100, "A", "G"), ("rs2", 1, 200, "C", "C"),
            ("rs3", 23, 300, "T", "T"), ("rs4", 2, 400, "0", "0"),
            ("rs5", 2, 500, "A", "A")]
    d = tempfile.mkdtemp()
    paths = {}

    paths["ancestry"] = os.path.join(d, "AncestryDNA.txt")
    with open(paths["ancestry"], "w", newline="\n") as fh:
        fh.write("#AncestryDNA raw data download\n")
        fh.write("rsid\tchromosome\tposition\tallele1\tallele2\n")
        for r, c, p, a, b in rows:
            fh.write("%s\t%d\t%d\t%s\t%s\n" % (r, c, p, a, b))

    paths["23andme"] = os.path.join(d, "23andme.txt")
    with open(paths["23andme"], "w", newline="\n") as fh:
        fh.write("# This data file generated by 23andMe\n")
        for r, c, p, a, b in rows:
            fh.write("%s\t%s\t%d\t%s\n" % (r, "X" if c == 23 else c, p,
                                           "--" if a == "0" else a + b))

    paths["generic"] = os.path.join(d, "ftdna.csv")
    paths["myheritage"] = os.path.join(d, "myheritage.csv")
    for key, hdr in (("generic", ""), ("myheritage", "# MyHeritage DNA raw data.\n")):
        with open(paths[key], "w", newline="\n") as fh:
            fh.write(hdr + "RSID,CHROMOSOME,POSITION,RESULT\n")
            for r, c, p, a, b in rows:
                fh.write('"%s","%s","%d","%s"\n'
                         % (r, "X" if c == 23 else c, p,
                            "--" if a == "0" else a + b))

    paths["vcf"] = os.path.join(d, "s.vcf")
    gts = {"AG": ("A", "G", "0/1"), "CC": ("C", "T", "0/0"),
           "TT": ("T", "C", "0/0"), "00": ("A", "G", "./."),
           "AA": ("A", "G", "0/0")}
    with open(paths["vcf"], "w", newline="\n") as fh:
        fh.write("##fileformat=VCFv4.2\n")
        fh.write("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1\n")
        for r, c, p, a, b in rows:
            ref, alt, gt = gts[(a + b) if a != "0" else "00"]
            fh.write("%s\t%d\t%s\t%s\t%s\t.\t.\t.\tGT\t%s\n"
                     % ("X" if c == 23 else c, p, r, ref, alt, gt))

    # unlabelled 4 column CSV is only claimed to be generic
    ref = None
    for want, path in paths.items():
        rec, fmt = chipio.read_chip(path)
        check("detect %s" % os.path.basename(path), fmt == want, "got %s" % fmt)
        got = [(str(rec["rsid"][i]), int(rec["chrom"][i]), int(rec["pos"][i]),
                "".join(sorted([rec["g1"][i], rec["g2"][i]])))
               for i in range(len(rec["rsid"]))]
        ref = ref or got
        check("parse %s matches" % os.path.basename(path), got == ref)
    check("no-calls marked", ref[3][3] == "00")
    check("X chromosome is 23", ref[2][1] == 23)

    # imputed VCF with fractional dosage and a quality score
    iv = os.path.join(d, "imputed.vcf")
    with open(iv, "w", newline="\n") as fh:
        fh.write("##fileformat=VCFv4.2\n")
        fh.write("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1\n")
        fh.write("1\t100\trs1\tA\tG\t.\t.\tDR2=0.95\tGT:DS\t0/1:0.900\n")
        fh.write("1\t200\trs2\tC\tT\t.\t.\tDR2=0.10\tGT:DS\t0/0:0.050\n")
    rec, fmt = chipio.read_chip(iv, min_r2=0.3)
    check("imputed VCF detected", fmt == "vcf (imputed dosages)", fmt)
    check("low R2 site dropped", rec["n_dropped_lowq"] == 1)
    check("dosage read", abs(float(rec["dose"][0]) - 0.9) < 1e-9)


def test_harmonize():
    print("marker matching strand flips and polarity")
    snp_id = np.array(["rs1", "rs2", "rs3", "rs4", "rs5"], dtype=object)
    chrom = np.array([1, 1, 1, 1, 1], dtype=np.int16)
    pos = np.array([100, 200, 300, 400, 500], dtype=np.int64)
    a1 = np.array(["A", "C", "A", "A", "G"], dtype="U1")
    a2 = np.array(["G", "T", "T", "G", "C"], dtype="U1")
    rec = {"rsid": snp_id.copy(), "chrom": chrom.copy(), "pos": pos.copy(),
           "g1": np.array(["A", "C", "A", "T", "G"], dtype="U1"),
           "g2": np.array(["G", "C", "A", "C", "G"], dtype="U1")}

    h = hz.harmonize(rec, snp_id, chrom, pos, a1, a2)
    s = h["stats"]
    by = {int(i): (int(d), bool(f), bool(am)) for i, d, f, am in
          zip(h["idx"], h["dose"], h["flipped"], h["ambiguous"])}
    check("all five matched", s["matched"] == 5)
    check("rs1 A/G het -> dose 1", by[0][0] == 1)
    check("rs2 CC -> dose 2", by[1][0] == 2)
    check("rs3 ambiguous A/T", by[2][2])
    check("rs4 T/C strand flipped", by[3][1])
    check("rs4 flipped -> dose 1", by[3][0] == 1)
    check("rs5 ambiguous G/C", by[4][2])
    check("one flip counted", s["strand_flipped"] == 1)
    check("drop-ambiguous removes both",
          len(hz.harmonize(rec, snp_id, chrom, pos, a1, a2,
                           drop_ambiguous=True)["idx"]) == 3)

    # only hets can prove a mismatch A/A at a C/T site is legal
    bad = dict(rec)
    bad["g1"] = np.array(["A", "A", "A", "T", "G"], dtype="U1")
    bad["g2"] = np.array(["G", "C", "A", "C", "G"], dtype="U1")
    check("impossible genotype dropped",
          hz.harmonize(bad, snp_id, chrom, pos, a1,
                       a2)["stats"]["dropped_allele_mismatch"] == 1)

    # at a non ambiguous site only one orientation can fit
    comp = {"A": "T", "T": "A", "C": "G", "G": "C"}
    bothfit = [(m1, m2, o1, o2) for m1 in "ACGT" for m2 in "ACGT"
               if m1 != m2 for o1 in "ACGT" for o2 in "ACGT"
               if (o1 in (m1, m2) and o2 in (m1, m2))
               and (comp[o1] in (m1, m2) and comp[o2] in (m1, m2))
               and comp[m1] != m2]
    check("strand always decidable at non-ambiguous sites", not bothfit,
          str(bothfit[:3]))

    rng = np.random.default_rng(0)
    p = rng.uniform(0.05, 0.95, 40000)
    dose = rng.binomial(2, p).astype(np.float32)
    amb = np.zeros(len(p), dtype=bool)
    sign, r, _ = hz.detect_polarity(dose, p, amb)
    check("polarity detects allele 1", sign == 1 and r > 0.4, "r=%.3f" % r)
    sign2, r2, _ = hz.detect_polarity(2.0 - dose, p, amb)
    check("polarity detects a flipped panel", sign2 == -1 and r2 < -0.4,
          "r=%.3f" % r2)


def test_packing():
    print("packed genotype bit layout")
    rng = np.random.default_rng(1)
    n_ind = 2003
    codes = rng.integers(0, 4, size=(7, n_ind)).astype(np.uint8)
    rlen = max(48, (n_ind + 3) // 4)
    padded = np.zeros((7, rlen * 4), dtype=np.uint8)
    padded[:, :n_ind] = codes
    raw = np.zeros((7, rlen), dtype=np.uint8)
    for i, sh in enumerate((6, 4, 2, 0)):
        raw |= (padded[:, i::4] << sh).astype(np.uint8)
    expect = codes.astype(np.int8)
    expect[expect == 3] = -1
    out = _unpack(raw, n_ind)
    check("unpack round-trips", np.array_equal(out, expect))
    check("missing code 3 -> -1", (out == -1).sum() == (codes == 3).sum())


def test_projection():
    print("projection algebra")
    rng = np.random.default_rng(2)
    n_snp, k = 4000, 6
    U = np.linalg.qr(rng.standard_normal((n_snp, k)))[0].astype(np.float32)
    sv = np.array([50.0, 40, 30, 20, 15, 10])
    true = rng.standard_normal((25, k)) * 0.1
    X = (U @ (true * sv).T).astype(np.float32)

    got = RestrictedBasis(U, sv).lsq(X)
    check("full marker set recovers scores", np.allclose(got, true, atol=1e-4),
          "max err %.2e" % np.abs(got - true).max())

    sel = np.sort(rng.permutation(n_snp)[:900])
    rb = RestrictedBasis(U[sel], sv)
    y_lsq, y_em, y_dot = rb.lsq(X[sel]), rb.em(X[sel]), rb.dot(X[sel])
    check("EM == least squares", np.allclose(y_lsq, y_em, atol=1e-8),
          "max diff %.2e" % np.abs(y_lsq - y_em).max())
    check("dot product is shrunk",
          np.abs(y_dot).mean() / np.abs(true).mean() < 0.5)
    check("least squares is not shrunk",
          abs(np.abs(y_lsq).mean() / np.abs(true).mean() - 1) < 0.15)

    W, b = fit_calibration(y_dot, true)
    check("calibration undoes the shrinkage",
          np.allclose(apply_calibration(y_dot, W, b), true, atol=1e-3))

    # weighting only helps with the calibration in the loop
    def degrade(Xc, r, gen):
        return (r[:, None] * Xc
                + gen.normal(0, np.sqrt(r * (1 - r))[:, None], Xc.shape))

    Xr = X + rng.standard_normal((n_snp, 25)).astype(np.float32)
    Ref = (U @ (rng.standard_normal((300, k)) * 0.1 * sv).T
           + rng.standard_normal((n_snp, 300))).astype(np.float32)
    r2 = np.clip(rng.uniform(0.2, 1.0, 900), 0.05, 1.0)
    Xw = degrade(Xr[sel], r2, rng)
    Rw = degrade(Ref[sel], r2, rng)
    errs = {}
    for lab, wts in (("unweighted", None), ("weighted", r2)):
        rbw = RestrictedBasis(U[sel], sv, weights=wts)
        W, b = fit_calibration(rbw.lsq(Rw),
                               RestrictedBasis(U[sel], sv).lsq(Ref[sel]))
        est = apply_calibration(rbw.lsq(Xw), W, b)
        errs[lab] = float(np.abs(est - RestrictedBasis(U[sel], sv).lsq(Xr[sel])).mean())
    check("reliability weighting does not hurt calibrated output",
          errs["weighted"] <= errs["unweighted"] * 1.02,
          "%.4f vs %.4f" % (errs["weighted"], errs["unweighted"]))

    obs = np.zeros((n_snp, 3), dtype=bool)
    for j in range(3):
        obs[rng.permutation(n_snp)[:1200 + 400 * j], j] = True
    per = lsq_per_individual(U, sv, np.where(obs, X[:, :3], 0.0).astype(np.float32),
                             obs)
    check("per-individual solve handles differing marker sets",
          np.allclose(per, true[:3], atol=2e-2))


def test_standardize():
    print("standardization")
    g = np.array([[0, 1, 2, -1]], dtype=np.int8)
    m2p, isd = standardization(np.array([0.5]))
    x = standardize(g, m2p, isd)
    check("centred on 2p", abs(float(x[0, 1])) < 1e-6)
    check("missing becomes zero", float(x[0, 3]) == 0.0)
    check("unit variance scaling",
          abs(float(x[0, 2]) - 1.0 / np.sqrt(0.5)) < 1e-6)


def main():
    for fn in (test_chip_formats, test_harmonize, test_packing,
               test_projection, test_standardize):
        fn()
        print()
    if FAILED:
        print("%d FAILED: %s" % (len(FAILED), ", ".join(FAILED)))
        return 1
    print("all self-tests passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
